title: My Site
description: A description of my site
url: https://haileyc.github.io/<repository-name>
baseurl:  # Leave blank if publishing to the root


remote_theme: "mmistakes/minimal-mistakes@4.27.3"
